language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: bDfI+6YEGw8VkFKiKLAZ67PNc8hJvjab6cmmsB9SR8E/ronpmSpi3zozXObdeQ1OmPlJedvl1z4BcS7ZVc0RmN+7kYA4Q1dyTaq+DA+fCsi1ZZ/glS5SQ4G0Vf83rSUkHB90Jb+zGWfjGTTvAHQEZBM187GSdsfit+kro7HkwjsPIhSgK7DwRXOU/qL/YjizzdEMtTTM+IHBp7jqK9oahxEkPp0OKDKsZ2NsI5hoMPLdW+EVOwl6JVm4uyKSlWdyJnAnGoYY5ZD7xVtJ8e1ZPqBZrYjQ2Q8/GbpfiK2akvBp+BmuLbi7y2iemqO//Ior5OS6VP5PuOrEFTg8m1qKBautg5yZRy1RuW+IWksUCO0qhL/LtACj+MXPIltN/WbkJko3/x4p0PdbMvgJbyq13bb4vxGXTvQR+5phxnh5oSJUKTosfIlEQQ8ynlJcWyxVhOkdKMq9ckdhVwdeqz+6iJWTswE42dbPAdvQgd8MsQ9YTh/4785q+crH77mJ1Xb+vaLi9k5ZMZg1XJM48NwmpUJz5llQGy63PjdCZyRgTeHHl6udMIqgIQ3uQupEeoyo3OjCxnZSW+tWuEGjjp+Mp43d0uFw+B7fkVl1hSZ1g2p1JzeFs4FnVFCGatmDfsJB2VSaBDtHpTiIY+ye+/52ZM4jA+tLfCBJ0NNrbgNS36g=
