language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: Hrmlgf6UOBYKK381LbjY9xkfrdHAO440w14BFmT/rzOMMaiiI/0ePAjzdnCTnszVb/d+9P72n5wlNKhAGMh785pUh+GPavWUrKJ9HTJx0BOqNAB96GQOJbbEvM811VpAG1mDsG2Z1FntoPdjk4YvsJh0HB0Qn0aFAHlKc3ayW6aZfmedSRRGhM95RVtw6G7bV/TmdmtUm7S4QuhkUWhWI9SVfZGzVpx6kEg021/6jbSzD3xoCt4C0sVGEoLn2juj25Zs+aG4xXoUu/TAe4ZDSifKcb7G53GRYPiDonGD7dOdaG0sDafd4INLO4bFX5ZevkljbdvhFpT4ff5but2cHnxrVh4a89gmXjGHJAsUGOPZOyCdo0WaK2KvlwxjwQLxoNTBVdSAldSEsqQRzGz4nyqXclHlR+wt30SseH5naX8NVy0tDiRexmy8zpnuAjJgYONDjN1JN29CK//0+HeWI7eSlzmY+OiDU5KA3Aamstk1Ia789iebJESD+RZ6HhZdovvDg2NvBjthErUEsHeZyKogzIEf8TWX5BdinJNHKtOpE9f4X/R7NXnuQYFrPd8sheP586ZXYdH5BE9wxM/HiE2zFRam8SCyeIGhmoE/vgPKekS9DB4+M9vhl52WBhcK71vNDxsPe6m+3sEL5y3/VZj4VbqljKBR1o0QgpziyGI=
  app: infinite-meadow-39275
